name: Deploy new version tag
on:
    workflow_dispatch:
        inputs:
            version:
                required: true
                type: number
jobs:
    deploy:
        runs-on: ubuntu-latest
        steps:
                # Test echo, will delete
              - run: |
                    echo The version is ${{ inputs.version }}
                    output_response = $(curl -L \
                        -H "Accept: application/vnd.github+json" \
                        -H "Authorization: github-actions ${{ secrets.GITHUB_TOKEN }}" \
                        -H "X-GitHub-Api-Version: 2022-11-28" \
                        https://api.github.com/repos/${{github.repository}}/pulls \
                    )
                    echo $output_response